### PR TITLE
DotBot: use P0.26 for AISEN motor driver

### LINKED ISSUE #13: motor driver: AISEN pin is not connected to an analog pin
So it's not possible to measure current consumed by the left motor using an ADC pin.
BISEN is connected P0.28 which is internally connected to AIN4.

### PR DESCRIPTION
**Pull request by aabadie**
fixes  #13

### CODE REVIEW

**Review by SaidAlvarado — CHANGES_REQUESTED** [review]
image

There is a clearance violation on the route of P0.26 close right below the Fanstel module.
Recommendation: Reduce the trace width from 0.3mm to 0.29mm.

**Comment by aabadie** [comment]
Should be fixed now

**Comment by SaidAlvarado** [comment]
Can confirm, that fixed the issue.
Everything looks OK.

**Review by SaidAlvarado — APPROVED** [review]
Nice job !

**Pull request merged**
